Repository geber-suprabapak/skanida-apps-mobile, pull requests merged in 2025-07, with the labels that each got.

#144 Integrates Sentry for error tracking and user feedback
  .gitignore
  app.json
  app/Dashboard.tsx
  app/_layout.tsx
  app/extra/pengaturan.tsx
  metro.config.js
  package.json
  pnpm-lock.yaml
Labels: enhancement

#158 Persiapan rilis closed beta test
  .github/dependabot.yml
  .gitignore
  app.json
  app/Dashboard.tsx
  app/_layout.tsx
  app/auth/Login.tsx
  app/auth/Register.tsx
  app/extra/pengaturan.tsx
  app/index.tsx
  app/profile/EditProfile.tsx
  components/ui/attendance-calendar.tsx
  metro.config.js
  package.json
  pnpm-lock.yaml
Labels: enhancement, high priority

#168 fix/textoverflow-perizinan
  app/perizinan/izin.tsx
Labels: bug

#170 Fix: Bug Close loop ketika back dari edit profile
  app/profile/EditProfile.tsx
Labels: enhancement
